[project]
name = "agentes-udemy"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "chromadb>=1.5.9",
    "dotenv>=0.9.9",
    "ipykernel>=7.2.0",
    "langchain>=1.2.7",
    "langchain-chroma>=1.1.0",
    "langchain-community>=0.4.2",
    "langchain-docling>=2.0.0",
    "langchain-openai>=1.1.7",
    "langchain-pymupdf4llm>=1.28.0",
    "langgraph>=1.0.7",
    "pathlib>=1.0.1",
    "pydantic>=2.12.5",
    "pypdf>=6.14.2",
    "pypdf2>=3.0.1",
    "pyproject-toml>=0.1.0",
    "python-pptx>=1.0.2",
    "streamlit>=1.53.1",
]
